### ISSUE TITLE
关于OnProcessShader 的疑问

### ISSUE THREAD

**Issue by zhaogd233** [lujian101/ShaderVariantCollector#1]
在编译Shader的时候，unity会自动根据变体，不编译不包含的shader_feature变体。
而你文中提到必须 包含multi_compile的变体。 那么自定义的OnProcessShader就没有意义了。

个人理解 onProcessShader的意义好像是根据变体，裁剪 multi_compile的变体吧。用multi_compile定义的变体，不一定非要包含在项目里面吧，毕竟理论上讲svc已经是完整的集合了。

**Comment by lujian101** [comment]
我在实际的处理中，确实在OnProcessShader中排除了大量不在SVC中的变体。SVC也并不完整，部分multi_compile是通过代码开关，变体收集过程中大概率不能完整记录，加上我个人对Unity某些新上的功能持怀疑态度，加上官方也没有明确说明OnProcessShade与SVC两者具体该怎么协作，所以所以自己决定结合两者剔除变体，实属拍脑袋想法。各个项目不同，还需多做一些实验验证才行。
