### ISSUE TITLE
怎么获取usepass的依赖shader？

### ISSUE THREAD

**Issue by wangxiao-github** [lujian101/ShaderVariantCollector#2]
怎么获取通过usepass依赖的shader呢？AssetDatabase.GetDependencies是获取不到的吧？2019.4版本是获取不到的。

**Comment by lujian101** [comment]
可以的，我刚把项目升级到2019，获取依赖之前，先把所有的Shader重新导入下就可以了，（鼠标右键点击Reimport）


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lujian101/ShaderVariantCollector"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月16日(星期二) 上午10:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lujian101/ShaderVariantCollector] 怎么获取usepass的依赖shader？ (#2)





 
怎么获取通过usepass依赖的shader呢？AssetDatabase.GetDependencies是获取不到的吧？2019.4版本是获取不到的。

**Comment by wangxiao-github** [comment]
确实，Reimport之后就可以了，多谢。看来import和Reimport操作还是有区别的，这是之前没想到的。
